//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pricing
    {
        public int id { get; set; }
        public string City_1 { get; set; }
        public string City_2 { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
