//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_admin
    {

        public int a_id { get; set; }

        [Required(ErrorMessage = "Admin Name Required")]
        [Display(Name = "Admin Name")]
        [MinLength(4, ErrorMessage = "Min 4 Character Required"), MaxLength(15, ErrorMessage = "Max 15 Character allow")]
        public string a_name { get; set; }


        [Required(ErrorMessage = "Admin Email Required")]
        [Display(Name = "Admin Email")]
        [MinLength(10, ErrorMessage = "Min 10 Character Required"), MaxLength(50, ErrorMessage = "Max 50 Character allow")]
        public string a_email { get; set; }


        [Required(ErrorMessage = "Admin Password Required")]
        [Display(Name = "Admin Password")]
        [MinLength(8, ErrorMessage = "Min 8 Character Required"), MaxLength(16, ErrorMessage = "Max 16 Character allow")]
        public string a_password { get; set; }
    }
}
