//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_customer
    {
        public int c_id { get; set; }

        [Required]
        [StringLength(15)]
        [Display(Name = "Customer Name")]
        public string c_name { get; set; }


        [Required]
        [StringLength(50)]
        [Display(Name = "Customer Address")]
        public string c_address { get; set; }


        [Required]
        [StringLength(13)]
        [Display(Name = "Customer Contact")]
        public string c_contact { get; set; }


        [Required]
        [StringLength(20)]
        [Display(Name = "Customer City")]
        public string c_city { get; set; }


        [Display(Name = "Customer Postcode")]
        public Nullable<int> c_postalcode { get; set; }


        [Required]
        [StringLength(15)]
        [Display(Name = "Customer Cnic")]
        public string c_CNIC { get; set; }


        [Display(Name = "Receiver Name")]
        [Required]
        [StringLength(15)]
        public string r_name { get; set; }


        [Required]
        [StringLength(50)]
        [Display(Name = "Receiver Address")]
        public string r_address { get; set; }


        [Required]
        [StringLength(13)]
        [Display(Name = "Receiver Contact")]
        public string r_contact { get; set; }


        [Required]
        [StringLength(20)]
        [Display(Name = "Receiver City")]
        public string r_city { get; set; }


        [Display(Name = "Receiver Postcode")]
        public Nullable<int> r_postalcode { get; set; }


        [Required]
        [StringLength(15)]
        [Display(Name = "Receiver Cnic")]
        public string r_CNIC { get; set; }


        //[Required(ErrorMessage = "Item Weight Required")]
        [Display(Name = "Item Weight")]
        public Nullable<int> item_weight { get; set; }


        //[Required(ErrorMessage = "Service Required")]
        [Display(Name = "Services")]
        //[MinLength(3, ErrorMessage = "Min 3 Character Required"), MaxLength(30, ErrorMessage = "Max 30 Character allow")]
        public string services { get; set; }


        public Nullable<System.DateTime> date { get; set; }


        [Required]
        [StringLength(30)]
        [Display(Name = "Delivery")]
        public string delivery { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> e_id { get; set; }

        [Display(Name = "Status")]
        public string status { get; set; }
    }
}

